import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import './globals.css';

import { cookies } from 'next/headers';

import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@/components/ui/sonner';
import TrpcProvider from '@/lib/trpc/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<TrpcProvider cookies={cookies().toString()}>{children}</TrpcProvider>
					<Toaster richColors />
				</ThemeProvider>
			</body>
		</html>
	);
}
